"""fix relationship 6

Revision ID: 024ce2d79f9f
Revises: 9f4a76f03750
Create Date: 2024-05-26 16:32:04.981383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024ce2d79f9f'
down_revision = '9f4a76f03750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('extra_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_column', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
