"""fix relationship 2

Revision ID: 4efc24173fb5
Revises: f466b7e8f14d
Create Date: 2024-05-26 15:44:57.796068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efc24173fb5'
down_revision = 'f466b7e8f14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('extra_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_column', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
