"""edit user serialize

Revision ID: 95818807607b
Revises: 04cd3137cd35
Create Date: 2024-06-04 21:06:08.197654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95818807607b'
down_revision = '04cd3137cd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
